# General Settings
title = "Wildrose Landscaping"
baseURL = "Wildroselandscaping.ca" 
languageCode = "en-us"
theme = "glacier"
resourceDir = "resources"
[pagination]
  pagerSize = 5
summaryLength = 50
DefaultContentLanguage = "en" # Site language. Available translations in the theme's `/i18n` directory.


# Menu Settings
[menu]
[[menu.main]]
    identifier = "parallax-home"
    name = "Parallax"
    url = "home"
    weight = 2
 [[menu.main]]
    identifier = "about"
    name = "about"
    url = "about"
    weight = 3
[[menu.main]]
    identifier = "pricing"
    name = "pricing"
    url = "pricing"
    weight = 4
[[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "Contact"
  weight = 5

# Main Settings
[params]
defaultLogo = "Wildrose"
defaultKeywords = ["wildrose", "landscaping", "blog", "responsive", "google analytics", "bootstrap", "portfolio", "personal", "modern", "parallax", "hugo theme", "creative"]
defaultDescription = "Wildrose Landscaping & Construction"
dateFormat = "January 2, 2006"
authorName = "Mountain-Themes"
disqusComments = "" #YOUR DISQUS COMMENTS SHORTNAME
formspreeFormID = "" #YOUR FORMSPREE FORM ID
reCAPTCHAKey = "" #YOUR reCAPTCHA v2 key
googleMapsApiKey = "" #YOUR GOOGLE API KEY

# Sidebar Settings
[params.sidebar]
enable = 1 #SIDEBAR SHOW: [ 1 - yes, 0 - no ] For General page "Blog"
position = "right" #SIDEBAR POSITION: [ left, right ] For General page "Blog"
search = 1 #SIDEBAR SEARCH WIDGET: [ 1 - yes, 0 - no ]
latestPosts = 1 #SIDEBAR LATEST POSTS WIDGET: [ 1 - yes, 0 - no ]
categories = 1 #SIDEBAR CATEGORIES TAXONOMY WIDGET: [ 1 - yes, 0 - no ]
tags = 1 #SIDEBAR TAG TAXONOMY WIDGET: [ 1 - yes, 0 - no ]



# Portfolio Settings (Filter)
[params.portfolio]
[[params.portfolio.filters]]
name = "Landscapes"
slug = "landscapes"
[[params.portfolio.filters]]
name = "Design"
slug = "design"
[[params.portfolio.filters]]
name = "Construction"
slug = "construction"

# Footer Settings
[params.footer]
copyright = "Glacier © 2024. Design & Coded by <a href='http://themeforest.net/user/Mountain-Themes' target='_blank'> Mountain-Themes.</a>"

# Sitemap Settings
[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[outputs]
home = ["HTML", "RSS", "JSON"]